CorePortfolio/Controllers/AnnouncementController.cs
using BusinnesLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CoreAnnouncement.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AnnouncementController : Controller
    {
        AnnouncementManager AnnouncementManager = new AnnouncementManager(new EfAnnouncementDal());
        public IActionResult Index()
        {
            var values = AnnouncementManager.TGetList().OrderByDescending(x=>x.Date).ToList();
            return View(values);
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddAnnouncement(Announcement Announcement)
        {
            Announcement.Status = "Aktif";
            Announcement.Date = DateTime.Now;
            AnnouncementManager.TAdd(Announcement);
            return RedirectToAction("Index");
        }

       
        public IActionResult Delete(int id)
        {

            var values = AnnouncementManager.TGetByID(id);
            AnnouncementManager.TDelete(values);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult AnnouncementDetails(int id)
        {
            Announcement announcement = AnnouncementManager.TGetByID(id);
            return View(announcement);
        }
    }
}

CorePortfolio/Views/Announcement/Add.cshtml
@{
    ViewData["Title"] = "Duyuru Ekle";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<form action="@Url.Action("AddAnnouncement","Announcement")" method="post">
    <div class="col-lg-12">
        <div class="row">
            <div class="form-group col-md-4">
                <label for="Title">Başlık</label>
                <input required type="text" class="form-control" id="Title" name="Title" placeholder="İçerik Başlığını Yazınız...">
            </div>
            </div>
            <div class="row">
            <div class="form-group col-md-12">
                <label for="Content">İçerik</label>
                <textarea required type="text" class="form-control" id="Content" name="Content" rows="3" maxlength="400" placeholder="İçeriği Yazınız..."></textarea>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-8">
                <button type="submit" class="btn btn-outline-info">Kaydet</button>
            </div>
        </div>
    </div>


</form>

CorePortfolio/Views/Announcement/AnnouncementDetails.cshtml
@using EntityLayer.Concrete;
@model Announcement
@{
    ViewData["Title"] = "Duyuru Detayları";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">@Model.Title</h4>
            <p class="description">@Model.Content</p>
            <p class="text-muted"><small><b>Duyuru Tarihi:</b> @Model.Date.ToString("dd MMM yyyy")  @Model.Date.ToString("HH:mm") </small></p>

        </div>
    </div>
</div>

CorePortfolio/Views/Announcement/Index.cshtml
@using EntityLayer.Concrete;
@model List<Announcement>
@{
    ViewData["Title"] = "Duyuru Listesi";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
    var status = "";
    var date = "";
}
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Duyurular</h4>
            <p class="card-description">
              "İncele" diyerek Duyurunun Detaylarına Gidebilirsiniz.
            </p>
            <p class="card-description">
                <a style="position:absolute;right:21px;top:22px;" href="@Url.Action("Add","Announcement")" class="btn btn-outline-success">Ekle</a>
            </p>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                        
                        <th></th>
                        <th>Başlık</th>
                        <th>Tarih</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {

                            TimeSpan day = (DateTime.Now - item.Date);
                            if (day.Days < 1 && item.Date.Day == DateTime.Now.Day && day.Hours < 1)
                                        {
                                status = "Yeni";
                                date = day.Minutes + " Dakika Önce";
                            }
                            else if (day.Days >= 1 && day.Days <= 4 )
                            {
                                status = null;
                                date = day.Days + " Gün Önce";
                            }
                            else if (day.TotalHours <= 23)
                            {
                                status = "Yeni";
                                date = day.Hours + " Saat Önce";
                            }
                            else if (day.Days > 4 && day.TotalHours > 23)
                            {
                                status = null;
                                date = item.Date.ToString("dd MMM yyyy");
                            }
                            <tr >
                               
                                @if (status != null)
                                {
                                    <td><label class="badge badge-outline-danger">@status</label></td>
                                }
                                else
                                {
                                    <td><label class="badge badge-outline-warning"><i style="font-size:20px;" class="mdi mdi-alert"></i></label></td>
                                }

                                <th>@item.Title</th>
                                <td>@date</td>
                                <td>
                                    <a href="#" id="profile-dropdown" data-toggle="dropdown"><i class="mdi mdi-dots-vertical"></i></a>
                                    <div class="dropdown-menu dropdown-menu-right sidebar-dropdown preview-list" aria-labelledby="profile-dropdown">
                                        
                                        <a href="/Announcement/Delete/@item.AnnouncementID" class="dropdown-item preview-item">
                                            <div class="preview-thumbnail">
                                            </div>
                                            <div class="preview-item-content">
                                                <p class="preview-subject ellipsis mb-1 text-small">Sil</p>
                                            </div>
                                        </a>
                                        <div class="dropdown-divider"></div>
                                        <a href="/Announcement/AnnouncementDetails/@item.AnnouncementID" class="dropdown-item preview-item">
                                            <div class="preview-thumbnail">
                                            </div>
                                            <div class="preview-item-content">
                                                <p class="preview-subject ellipsis mb-1 text-small">İncele</p>
                                            </div>
                                        </a>
                                    </div>
                                </td>
                            </tr>

                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>