CorePortfolio/Controllers/AboutController.cs
using BusinnesLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CorePortfolio.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AboutController : Controller
    {
        AboutManager aboutManager = new AboutManager(new EfAboutDal());

        [HttpGet]
        public IActionResult Index()
        {
            var values = aboutManager.TGetByID(3);
            return View(values);
        }
        [HttpPost]
        public IActionResult UpdateAbout(About about)
        {
            aboutManager.TUpdate(about);
            return RedirectToAction("Index", "Default");
        }
    }
}

CorePortfolio/Controllers/FeatureController.cs
using BusinnesLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CorePortfolio.Controllers
{
    [Authorize(Roles = "Admin")]
    public class FeatureController : Controller
    {
        FeatureManager fManager = new FeatureManager(new EfFeatureDal());
        
        [HttpGet]
        public IActionResult Index()
        {
            
            var values = fManager.TGetByID(1);
            return View(values);
        }
        [HttpPost]
        public IActionResult UpdateFeature(Feature feature)
        {
            
            fManager.TUpdate(feature);


            return RedirectToAction("Index","Default");
        }
    }
}

CorePortfolio/Controllers/ServiceController.cs
using BusinnesLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CorePortfolio.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ServiceController : Controller
    {
        ServiceManager serviceManager = new ServiceManager(new EfServiceDal());
        public IActionResult Index()
        {
            var values= serviceManager.TGetList();
            return View(values);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddService(Service service)
        {
            service.CreationDate = DateTime.Now;
            service.UpdatedDate = DateTime.Now;
            serviceManager.TAdd(service);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            var values = serviceManager.TGetByID(id);
            serviceManager.TDelete(values);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Update(int id)
        {
            var values = serviceManager.TGetByID(id);

            return View(values);
        }
        [HttpPost]
        public IActionResult UpdateService(Service service)
        {
            service.UpdatedDate = DateTime.Now;
            serviceManager.TUpdate(service);
            return RedirectToAction("Index");
        }

    }
}

CorePortfolio/Controllers/SkillController.cs
using BusinnesLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CorePortfolio.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SkillController : Controller
    {
        SkillManager skillManager=new SkillManager(new EfSkillDal());
        public IActionResult Index()
        {
            var values=skillManager.TGetList();
            return View(values);
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddSkill(Skill skill)
        {
            skillManager.TAdd(skill);
            skill.CreationDate = DateTime.Now;
            skill.UpdatedDate = DateTime.Now;
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            var values=skillManager.TGetByID(id);
            skillManager.TDelete(values);

            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Update(int id)
        {
            var values = skillManager.TGetByID(id);
            return View(values);
        }
        [HttpPost]
        public IActionResult UpdateSkill(Skill skill)
        {
            skill.UpdatedDate = DateTime.Now;
           skillManager.TUpdate(skill);
            return RedirectToAction("Index");
        }
    }
}

CorePortfolio/Views/Admin/AdminFooterPartial.cshtml
<footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © Okan Akın 2023</span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"><a href="https://okannakinns.github.io/Portfolio/" target="_blank">Okan Akın</a></span>
    </div>
</footer>

CorePortfolio/Views/Admin/AdminHeadPartial.cshtml
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - Admin</title>
    <!-- plugins:css -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/vendors/css/vendor.bundle.base.css">

    <link rel="stylesheet" href="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/vendors/jvectormap/jquery-jvectormap.css">
    <link rel="stylesheet" href="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/vendors/flag-icon-css/css/flag-icon.min.css">
    <link rel="stylesheet" href="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/vendors/owl-carousel-2/owl.carousel.min.css">
    <link rel="stylesheet" href="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/vendors/owl-carousel-2/owl.theme.default.min.css">

    <!-- End plugin css for this page -->
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/css/style.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/images/favicon.png" />
    <link href="~/Template/css/font-awesome/css/all.min.css?ver=1.2.0" rel="stylesheet">
</head>

CorePortfolio/Views/Admin/AdminNavbarPartial.cshtml
<nav class="navbar p-0 fixed-top d-flex flex-row">
    <div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
        <a class="navbar-brand brand-logo-mini" href="/Dashboard/Index"><i class="fas fa-map"></i></a>
    </div>
    <div class="navbar-menu-wrapper flex-grow d-flex align-items-stretch">
        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="mdi mdi-menu"></span>
        </button>
        <ul class="navbar-nav w-100">
            <li class="nav-item w-100">
                <form class="nav-link mt-2 mt-md-0 d-none d-lg-flex search">
                    <input type="text" class="form-control" placeholder="Ara">
                </form>
            </li>
        </ul>
        <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item dropdown d-none d-lg-block">
                <a class="nav-link btn btn-success create-new-button" id="createbuttonDropdown" data-toggle="dropdown" aria-expanded="false" href="#">+ Hızlı Ekleme</a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="createbuttonDropdown">
                    <h6 class="p-3 mb-0">Hızlı Ekle</h6>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item" href="/Portfolio/Add">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-dark rounded-circle">
                                <i class="mdi mdi-file-outline text-primary"></i>
                            </div>
                        </div>
                        <div class="preview-item-content">
                            <p class="preview-subject ellipsis mb-1">Proje Ekle</p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item" href="/Experience/Add">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-dark rounded-circle">
                                <i class="mdi mdi-web text-info"></i>
                            </div>
                        </div>
                        <div class="preview-item-content">
                            <p class="preview-subject ellipsis mb-1">Deneyim Ekle</p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item" href="/SocialMedia/Add">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-dark rounded-circle">
                                <i class="mdi mdi-layers text-danger"></i>
                            </div>
                        </div>
                        <div class="preview-item-content">
                            <p class="preview-subject ellipsis mb-1">Sosyal Medya Ekle</p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item" href="/Announcement/Add">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-dark rounded-circle">
                                <i class="mdi mdi-layers text-danger"></i>
                            </div>
                        </div>
                        <div class="preview-item-content">
                            <p class="preview-subject ellipsis mb-1">Duyuru Ekle</p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <p class="p-3 mb-0 text-center"><a href="/Dashboard/Index">Ana Sayfaya Dön</a></p>
                </div>
            </li>
           
            @await Component.InvokeAsync("AdminNavbarMessageList")
            <li class="nav-item dropdown border-left">
                <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
                    <i class="mdi mdi-bell"></i>
                    <span class="count bg-danger"></span>
                </a>
               @await Component.InvokeAsync("AdminNotifications")
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link" id="profileDropdown" href="#" data-toggle="dropdown">
                    <div class="navbar-profile">
                        <img class="img-xs rounded-circle" src="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/images/faces/adminpic.png" alt="">
                        <p class="mb-0 d-none d-sm-block navbar-profile-name">@ViewBag.UserName</p>
                        <i class="mdi mdi-menu-down d-none d-sm-block"></i>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="profileDropdown">
                    <h6 class="p-3 mb-0">Profil</h6>
                    <div class="dropdown-divider"></div>
                    <a href="/ProfileSettings/Index" class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-dark rounded-circle">
                                <i class="mdi mdi-settings text-success"></i>
                            </div>
                        </div>
                        <div class="preview-item-content">
                            <p class="preview-subject mb-1">Ayarlar</p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="/User/Login/LogOut" class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-dark rounded-circle">
                                <i class="mdi mdi-logout text-danger"></i>
                            </div>
                        </div>
                        <div class="preview-item-content">
                            <p class="preview-subject mb-1">Çıkış Yap</p>
                        </div>
                    </a>
                    @*<div class="dropdown-divider"></div>
                    <p class="p-3 mb-0 text-center">Advanced settings</p>*@
                </div>
            </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="mdi mdi-format-line-spacing"></span>
        </button>
    </div>
</nav>

CorePortfolio/Views/Admin/AdminScriptsPartial.cshtml
<!-- container-scroller -->
<!-- plugins:js -->
<script src="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/vendors/js/vendor.bundle.base.js"></script>
<!-- endinject -->
<!-- Plugin js for this page -->
<!-- End plugin js for this page -->
<!-- inject:js -->
<script src="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/js/off-canvas.js"></script>
<script src="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/js/hoverable-collapse.js"></script>
<script src="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/js/misc.js"></script>
<script src="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/js/settings.js"></script>
<script src="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/js/todolist.js"></script>


<script src="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/vendors/chart.js/Chart.min.js"></script>
<script src="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/vendors/progressbar.js/progressbar.min.js"></script>
<script src="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/vendors/jvectormap/jquery-jvectormap.min.js"></script>
<script src="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/vendors/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<script src="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/vendors/owl-carousel-2/owl.carousel.min.js"></script>

<script src="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/js/dashboard.js"></script>

CorePortfolio/Views/Admin/AdminSidebarPartial.cshtml
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <div class="sidebar-brand-wrapper d-none d-lg-flex align-items-center justify-content-center fixed-top">
        <a class="sidebar-brand brand-logo" href="@Url.Action("Index","Dashboard")">ADMIN</a>
        <a class="sidebar-brand brand-logo-mini" href="@Url.Action("Index","Dashboard")"><i class="fas fa-map"></i></a>
    </div>
    <ul class="nav">
        <li class="nav-item profile">
            <div class="profile-desc">
                <div class="profile-pic">
                    <div class="count-indicator">
                        <img class="img-xs rounded-circle " src="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/images/faces/adminpic.png" alt="">
                        <span class="count bg-success"></span>
                    </div>
                   @await Component.InvokeAsync("SidebarAdminInfo")
                </div>
                <a href="#" id="profile-dropdown" data-toggle="dropdown"><i class="mdi mdi-dots-vertical"></i></a>
                <div class="dropdown-menu dropdown-menu-right sidebar-dropdown preview-list" aria-labelledby="profile-dropdown">
                    <a href="/ProfileSettings/Index" class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-dark rounded-circle">
                                <i style="font-size:20px" class="mdi mdi-settings text-primary"></i>
                            </div>
                        </div>
                        <div class="preview-item-content">
                            <p class="preview-subject ellipsis mb-1 text-small">Hesap Ayarları</p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="/Default/Index" class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-dark rounded-circle">
                                <i style="font-size:20px" class="mdi mdi-format-horizontal-align-left  text-info"></i>
                            </div>
                        </div>
                        <div class="preview-item-content">
                            <p class="preview-subject ellipsis mb-1 text-small">Siteye Dön</p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="User/Login/LogOut" class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-dark rounded-circle">
                                <i style="font-size:20px" class="mdi mdi-logout text-danger"></i>
                            </div>
                        </div>
                        <div class="preview-item-content">
                            <p class="preview-subject ellipsis mb-1 text-small">Çıkış Yap</p>
                        </div>
                    </a>
                </div>
            </div>
        </li>
        <li class="nav-item nav-category">
            <span class="nav-link">Navigasyon</span>
        </li>
        <li class="nav-item menu-items">
            <a class="nav-link" href="@Url.Action("Index","Dashboard")">
                <span class="menu-icon">
                    <i style="font-size:20px" class="mdi mdi-home"></i>
                </span>
                <span class="menu-title">Ana Sayfa</span>
            </a>
        </li>
        <li class="nav-item menu-items">
            <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
                <span class="menu-icon">
                    <i style="font-size:20px" class="mdi mdi-message-processing"></i>
                </span>
                <span class="menu-title">İletişim</span>
                <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="ui-basic">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"> <a class="nav-link" href="/Contact/Index">İletişim Bilgileri</a></li>
                    <li class="nav-item"> <a class="nav-link" href="@Url.Action("Index","ContactMessage")">İletişim Mesajları</a></li>

                </ul>
            </div>
        </li>
        <li class="nav-item menu-items">
            <a class="nav-link" href="@Url.Action("Index","UserList")">
                <span class="menu-icon">
                    <i style="font-size:20px" class="mdi mdi-account"></i>
                </span>
                <span class="menu-title">Kullanıcılar</span>
            </a>
        </li>
        <li class="nav-item menu-items">
            <a class="nav-link" data-toggle="collapse" href="#auth" aria-expanded="false" aria-controls="auth">
                <span class="menu-icon">
                    <i style="font-size:20px" class="mdi mdi-message-text"></i>
                </span>
                <span class="menu-title">Kullanıcı Mesajları</span>
                <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="auth">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"> <a class="nav-link" href="/AdminMessage/CreateNewMessage">Yeni Mesaj Oluştur</a></li>
                    <li class="nav-item"> <a class="nav-link" href="/AdminMessage/ReceiverMessageList">Gelen Kutusu</a></li>
                    <li class="nav-item"> <a class="nav-link" href="/AdminMessage/SenderMessageList">Giden Kutusu</a></li>

                </ul>
            </div>
        </li>
        
        <li class="nav-item menu-items">
            <a class="nav-link" href="@Url.Action("Index","Announcement")">
                <span class="menu-icon">
                    <i style="font-size:20px" class="mdi mdi-alert"></i>
                </span>
                <span class="menu-title">Duyurular</span>
            </a>
        </li>
        <li class="nav-item menu-items">
            <a class="nav-link" href="@Url.Action("Index","Feature")">
                <span class="menu-icon">
                    <i style="font-size:20px" class="mdi mdi-playlist-play"></i>
                </span>
                <span class="menu-title">Öne Çıkanlar</span>
            </a>
        </li>
        <li class="nav-item menu-items">
            <a class="nav-link" href="@Url.Action("Index","About")">
                <span class="menu-icon">
                    <i style="font-size:20px" class="mdi mdi-account-card-details"></i>
                </span>
                <span class="menu-title">Hakkımda</span>
            </a>
        </li>
        <li class="nav-item menu-items">
            <a class="nav-link" href="@Url.Action("Index","Service")">
                <span class="menu-icon">
                    <i style="font-size:20px" class="mdi mdi-briefcase"></i>
                </span>
                <span class="menu-title">Hizmetler</span>
            </a>
        </li>
        <li class="nav-item menu-items">
            <a class="nav-link" href="@Url.Action("Index","Skill")">
                <span class="menu-icon">
                    <i style="font-size:20px" class="mdi mdi-star"></i>
                </span>
                <span class="menu-title">Yetenekler</span>
            </a>
        </li>
        <li class="nav-item menu-items">
            <a class="nav-link" href="@Url.Action("Index","Portfolio")">
                <span class="menu-icon">
                    <i style="font-size:20px" class="mdi mdi-chart-bar"></i>
                </span>
                <span class="menu-title">Projeler</span>
            </a>
        </li>
        <li class="nav-item menu-items">
            <a class="nav-link" href="@Url.Action("Index","Experience")">
                <span class="menu-icon">
                    <i style="font-size:20px" class="mdi mdi-contacts"></i>
                </span>
                <span class="menu-title">Deneyimler</span>
            </a>
        </li>
        <li class="nav-item menu-items">
            <a class="nav-link" href="@Url.Action("Index","Testimonial")">
                <span class="menu-icon">
                    <i style="font-size:20px" class="mdi mdi-thumb-up"></i>
                </span>
                <span class="menu-title">Referanslar</span>
            </a>

        </li>
        <li class="nav-item menu-items">
            <a class="nav-link" href="@Url.Action("Index","SocialMedia")">
                <span class="menu-icon">
                    <i style="font-size:20px" class="mdi mdi-github-circle"></i>
                </span>
                <span class="menu-title">Sosyal Medya</span>
            </a>
        </li>
       
    </ul>
</nav>