CorePortfolio/Areas/User/Controllers/TestimonialController.cs
using BusinnesLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CorePortfolio.Areas.User.Controllers
{
    [Authorize(Roles ="User")]
    [Area("User")]
    public class TestimonialController : Controller
    {
        TestimonialManager testimonialManager = new TestimonialManager(new EfTestimonialDal());
        private readonly UserManager<WriterUser> _userManager;

        public TestimonialController(UserManager<WriterUser> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            var name = user.Name + " " + user.SurName;
            var value = testimonialManager.TGetList().Where(x => x.ClientName == name).FirstOrDefault();

            return View(value);
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var value = testimonialManager.TGetByID(id);
            testimonialManager.TDelete(value);

            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            var name = user.Name + " " + user.SurName;
            ViewBag.NameAndSurname = name;
            return View();
        }
        [HttpGet]
        public IActionResult Update(int id)
        {
            var value = testimonialManager.TGetByID(id);
            return View(value);
        }
        [HttpGet]
        public IActionResult TestimonialDetails(int id)
        {
            Testimonial testimonial = testimonialManager.TGetByID(id);
            return View(testimonial);
        }
        [HttpPost]
        public async Task<IActionResult> AddTestimonial(Testimonial testimonial)
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            testimonial.ClientName= user.Name + " " + user.SurName;
            testimonial.CreationDate = DateTime.Now;
            testimonial.ImageUrl = "/Template/images/testimonials/userpic.png";
            testimonialManager.TAdd(testimonial);

            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult UpdateTestimonial(Testimonial testimonial)
        {
            testimonial.UpdatedDate = DateTime.Now;
            testimonialManager.TUpdate(testimonial);
            return RedirectToAction("Index");
        }
    }
}

CorePortfolio/Controllers/TestimonialController.cs
using BusinnesLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CorePortfolio.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TestimonialController : Controller
    {
        TestimonialManager testimonialManager = new TestimonialManager(new EfTestimonialDal());
        public IActionResult Index()
        {
            var values=testimonialManager.TGetList();

            return View(values);
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var value=testimonialManager.TGetByID(id);
            testimonialManager.TDelete(value);

            return RedirectToAction("Index");
        }
     
        
        [HttpGet]
        public IActionResult TestimonialDetails(int id)
        {
            Testimonial testimonial = testimonialManager.TGetByID(id);
            return View(testimonial);
        }
        
    }
}

CorePortfolio/Areas/User/Views/Testimonial/Add.cshtml
@{
    ViewData["Title"] = "Referans Yorumu Ekle";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}


<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Referans Yorumu Ekleme</h4>
                <p class="card-description">
                    Aşağıdaki yerleri doldurarak yorum gönderebilirsiniz.
                </p>
                <form class="forms-sample" method="post">

                    <div class="form-group">
                        <div class="col-md-6">
                            <label for="ClientName">Ad Soyad</label>
                            <input readonly type="text" class="form-control" id="ClientName" name="ClientName" value="@ViewBag.NameAndSurname">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <label for="Company">Şirket</label>
                            <input type="text" class="form-control" id="Company" name="Company" placeholder="Şirket İsmi">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <label for="Title">Pozisyon</label>
                            <input type="text" class="form-control" id="Title" name="Title" placeholder="Örn:Ios Developer">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <label for="Comment">Yorum</label>
                            <textarea type="text" class="form-control" id="Comment" rows="3" maxlength="400" minlenght="20" name="Comment" placeholder="Yorum"></textarea>
                        </div>
                    </div>
                    <div class="col-md-5">
                        <button asp-controller="Testimonial" asp-action="AddTestimonial" class="btn btn-primary mr-2">Kaydet</button>

                    </div>
                </form>
            </div>
        </div>
    </div>

</div>

CorePortfolio/Areas/User/Views/Testimonial/Index.cshtml
@using EntityLayer.Concrete;
@model Testimonial
@{
    ViewData["Title"] = "Referans Yorumlarım";
    Layout = "~/Views/Shared/_UserLayout.cshtml";

}
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Referans Yorumlarım</h4>
                <p class="description">Yorumunuzu Paylaşırken Ad Soyad Bölümü Kullanıcı Bilgilerinizle Aynı Olmalıdır.</p>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Ad Soyad</th>
                                <th>Şirket</th>
                                <th>Pozisyon</th>
                                <th>İşlemler</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tbody>
                                @if (Model == null)
                                {
                                    <tr>
                                    <td style="font-weight:bold;">Hiç Yorumunuz Bulunmamaktadır.Yorum Yapmak İçin <a href="/User/Testimonial/Add">Tıklayınız</a></td>
                                    </tr>
                                }
                                else
                                {
                                    
                                    <tr>

                                        <td>@Model.ClientName</td>
                                        <td>@Model.Company</td>
                                        <td>@Model.Title</td>

                                        <td>

                                        <a href="/User/Testimonial/Delete/@Model.TestimonialID" class="btn btn-danger btn-sm">Sil</a>
                                        <a href="/User/Testimonial/Update/@Model.TestimonialID" class="btn btn-info btn-sm">Güncelle</a>
                                        <a href="/User/Testimonial/TestimonialDetails/@Model.TestimonialID" class="btn btn-primary btn-sm">İncele</a>
                                        </td>



                                    </tr>
                                    
                                }
                                
                        </tbody>
                      
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>

CorePortfolio/Areas/User/Views/Testimonial/Update.cshtml
@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Referans Yorumu Ekleme</h4>
                <p class="card-description">
                    Aşağıdaki yerleri doldurarak yorum gönderebilirsiniz.
                </p>
                <form class="forms-sample" method="post">

                    <div class="form-group">
                        <div class="col-md-6">
                            <label for="ClientName">Ad Soyad</label>
                            <input type="text" class="form-control" id="ClientName" name="ClientName" placeholder="Kullanıcı Bilgileriniz İle Aynı Olmalıdır" value="@Model.ClientName">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <label for="Company">Şirket</label>
                            <input type="text" class="form-control" id="Company" name="Company" placeholder="Şirket İsmi" value="@Model.Company">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <label for="Title">Pozisyon</label>
                            <input type="text" class="form-control" id="Title" name="Title" placeholder="Örn:Ios Developer" value="@Model.Title">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <label for="Comment">Yorum</label>
                            <textarea type="text" class="form-control" id="Comment" rows="3" maxlength="400" minlenght="20" name="Comment" placeholder="Yorum">@Model.Comment</textarea>
                        </div>
                    </div>
                    <div class="col-md-5">
                        <button asp-controller="Testimonial" asp-action="AddTestimonial" class="btn btn-primary mr-2">Kaydet</button>

                    </div>
                </form>
            </div>
        </div>
    </div>

</div>